# Generated by Django 5.1.7 on 2025-03-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('vet_name', models.CharField(max_length=100)),
            ],
        ),
    ]
